added cron job for queues

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -34,8 +34,13 @@ jobs:
       - name: Pull Environment Variables from Vercel
         run: vercel env pull .env --token=${{ secrets.VERCEL_TOKEN }}
 
-      - name: Migrate DB
-        run: php artisan migrate --force
+      - name: Symlink of public folder
+        run: |
+          if [ ! -L public/storage ]; then
+            php artisan storage link || echo "Symbolic link already exists or there was an error."
+          else
+            echo "Symbolic link already exists."
+          fi
         env:
           APP_ENV: production
           DB_CONNECTION: pgsql
@@ -44,5 +49,12 @@ jobs:
           DB_DATABASE: ${{ secrets.DB_DATABASE }}
           DB_USERNAME: ${{ secrets.DB_USERNAME }}
           DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+
+      - name: Migrate DB
+        run: php artisan migrate --force
+        
+      - name: Seeding  DB
+        run: php artisan db seed --force
+
       - name: Deploy to Vercel
         run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
